version: '3.1'
services:
  postgres:
    image: postgres:14
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret_follow
      POSTGRES_USER: follow
      POSTGRES_DB: trace
    ports:
      - 5432:5432